[package]
authors       = { workspace = true }
categories    = { workspace = true }
description   = '☢️ Data models used across the Power Plant ecosystem.'
documentation = 'https://docs.rs/power-plant'
edition       = { workspace = true }
homepage      = { workspace = true }
keywords      = { workspace = true }
license       = { workspace = true }
name          = 'power-plant-models'
publish       = true
readme        = './README.md'
repository    = { workspace = true }
version       = '0.1.7'

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
chrono     = { workspace = true, features = ['serde'] }
serde      = { workspace = true, features = ['derive'], optional = true }
serde_json = { workspace = true }
uuid       = { workspace = true }

[features]
default = ['serde']
serde   = ['dep:serde']
