rules:
  template-injection:
    ignore:
      - release.yml
  dangerous-triggers:
    ignore:
      - greetings.yml:3:1
  unpinned-uses:
    ignore:
      - release.yml:39:15
      - release.yml:135:15
      - release.yml:253:15
      - release.yml:304:15
      - release.yml:332:15
      - release.yml:359:15
      - dependabot-update.yml:29:15
      - codeql.yml:67:15
      - security.yml:21:11
      - security.yml:33:11
      - schedule-stale.yml:20:15
      - schedule-stale.yml:36:15
      - schedule-stale.yml:52:15
      - schedule-stale.yml:68:15
      - schedule-stale.yml:84:15
      - schedule-stale.yml:100:15
      - schedule-stale.yml:116:15
      - schedule-stale.yml:132:15
      - schedule-stale.yml:148:15
      - schedule-stale.yml:164:15
  excessive-permissions:
    ignore:
      - release.yml
      - zizmor.yml
      - sync-labels.yml
      - lock.yml
      - git-guardian.yml
