use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Default, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum SourceCodeLanguage {
  #[default]
  TypeScript,
  Ada,
  Agda,
  Apex,
  Assembly,
  Astro,
  Awk,
  Bash,
  Beancount,
  Bibtex,
  Bicep,
  Bitbake,
  Blade,
  C,
  CSharp,
  Cairo,
  Capnp,
  Cfml,
  Cfscript,
  Clojure,
  Cmake,
  Cobol,
  Commonlisp,
  Cpp,
  Crystal,
  Css,
  Csv,
  Cuda,
  D,
  Dart,
  Devicetree,
  Diff,
  Dockerfile,
  Dotenv,
  Elisp,
  Elixir,
  Elm,
  Erlang,
  Fennel,
  Fish,
  Form,
  Fortran,
  FSharp,
  Func,
  Gdscript,
  Gitattributes,
  Gitignore,
  Gleam,
  Glsl,
  Gn,
  Go,
  Gomod,
  Gotemplate,
  Graphql,
  Groovy,
  Hare,
  Haskell,
  Hcl,
  Hlsl,
  Html,
  Hyprlang,
  Ini,
  Ispc,
  Janet,
  Java,
  JavaScript,
  Jinja2,
  Jsdoc,
  Json,
  Json5,
  Jsonnet,
  Julia,
  Just,
  Kconfig,
  Kdl,
  Kotlin,
  Lean,
  Linkerscript,
  Liquid,
  Llvm,
  Lua,
  Luau,
  Magma,
  Make,
  Markdown,
  Matlab,
  Mermaid,
  Meson,
  Mojo,
  Move,
  Nasm,
  Nickel,
  Nix,
  Objc,
  ObjectscriptRoutine,
  ObjectscriptUdl,
  Ocaml,
  Odin,
  Pascal,
  Perl,
  Php,
  Pine,
  Pkl,
  Po,
  Pony,
  Powershell,
  Prisma,
  Properties,
  Protobuf,
  Puppet,
  Purescript,
  Python,
  Qml,
  R,
  Racket,
  Regex,
  Requirements,
  Rescript,
  Ron,
  Rst,
  Ruby,
  Rust,
  Scala,
  Scheme,
  Scss,
  Slang,
  Smali,
  Smithy,
  Solidity,
  Soql,
  Sosl,
  Sql,
  Squirrel,
  Sshconfig,
  Starlark,
  Svelte,
  Sway,
  Swift,
  Systemverilog,
  Tablegen,
  Tcl,
  Teal,
  Templ,
  Thrift,
  Tlaplus,
  Toml,
  Tsx,
  Typst,
  Verilog,
  Vhdl,
  Vim,
  Vue,
  Wgsl,
  Wit,
  Wolfram,
  Xml,
  Yaml,
  Zig,
  Zsh,
}

impl SourceCodeLanguage {
  pub fn as_str(&self) -> &str {
    match self {
      SourceCodeLanguage::Ada => "ada",
      SourceCodeLanguage::Agda => "agda",
      SourceCodeLanguage::Apex => "apex",
      SourceCodeLanguage::Assembly => "assembly",
      SourceCodeLanguage::Astro => "astro",
      SourceCodeLanguage::Awk => "awk",
      SourceCodeLanguage::Bash => "bash",
      SourceCodeLanguage::Beancount => "beancount",
      SourceCodeLanguage::Bibtex => "bibtex",
      SourceCodeLanguage::Bicep => "bicep",
      SourceCodeLanguage::Bitbake => "bitbake",
      SourceCodeLanguage::Blade => "blade",
      SourceCodeLanguage::C => "c",
      SourceCodeLanguage::CSharp => "c_sharp",
      SourceCodeLanguage::Cairo => "cairo",
      SourceCodeLanguage::Capnp => "capnp",
      SourceCodeLanguage::Cfml => "cfml",
      SourceCodeLanguage::Cfscript => "cfscript",
      SourceCodeLanguage::Clojure => "clojure",
      SourceCodeLanguage::Cmake => "cmake",
      SourceCodeLanguage::Cobol => "cobol",
      SourceCodeLanguage::Commonlisp => "commonlisp",
      SourceCodeLanguage::Cpp => "cpp",
      SourceCodeLanguage::Crystal => "crystal",
      SourceCodeLanguage::Css => "css",
      SourceCodeLanguage::Csv => "csv",
      SourceCodeLanguage::Cuda => "cuda",
      SourceCodeLanguage::D => "d",
      SourceCodeLanguage::Dart => "dart",
      SourceCodeLanguage::Devicetree => "devicetree",
      SourceCodeLanguage::Diff => "diff",
      SourceCodeLanguage::Dockerfile => "dockerfile",
      SourceCodeLanguage::Dotenv => "dotenv",
      SourceCodeLanguage::Elisp => "elisp",
      SourceCodeLanguage::Elixir => "elixir",
      SourceCodeLanguage::Elm => "elm",
      SourceCodeLanguage::Erlang => "erlang",
      SourceCodeLanguage::Fennel => "fennel",
      SourceCodeLanguage::Fish => "fish",
      SourceCodeLanguage::Form => "form",
      SourceCodeLanguage::Fortran => "fortran",
      SourceCodeLanguage::FSharp => "fsharp",
      SourceCodeLanguage::Func => "func",
      SourceCodeLanguage::Gdscript => "gdscript",
      SourceCodeLanguage::Gitattributes => "gitattributes",
      SourceCodeLanguage::Gitignore => "gitignore",
      SourceCodeLanguage::Gleam => "gleam",
      SourceCodeLanguage::Glsl => "glsl",
      SourceCodeLanguage::Gn => "gn",
      SourceCodeLanguage::Go => "go",
      SourceCodeLanguage::Gomod => "gomod",
      SourceCodeLanguage::Gotemplate => "gotemplate",
      SourceCodeLanguage::Graphql => "graphql",
      SourceCodeLanguage::Groovy => "groovy",
      SourceCodeLanguage::Hare => "hare",
      SourceCodeLanguage::Haskell => "haskell",
      SourceCodeLanguage::Hcl => "hcl",
      SourceCodeLanguage::Hlsl => "hlsl",
      SourceCodeLanguage::Html => "html",
      SourceCodeLanguage::Hyprlang => "hyprlang",
      SourceCodeLanguage::Ini => "ini",
      SourceCodeLanguage::Ispc => "ispc",
      SourceCodeLanguage::Janet => "janet",
      SourceCodeLanguage::Java => "java",
      SourceCodeLanguage::Python => "python",
      SourceCodeLanguage::Rust => "rust",
      SourceCodeLanguage::JavaScript => "javascript",
      SourceCodeLanguage::Jinja2 => "jinja2",
      SourceCodeLanguage::Jsdoc => "jsdoc",
      SourceCodeLanguage::Json => "json",
      SourceCodeLanguage::Json5 => "json5",
      SourceCodeLanguage::Jsonnet => "jsonnet",
      SourceCodeLanguage::Julia => "julia",
      SourceCodeLanguage::Just => "just",
      SourceCodeLanguage::Kconfig => "kconfig",
      SourceCodeLanguage::Kdl => "kdl",
      SourceCodeLanguage::Kotlin => "kotlin",
      SourceCodeLanguage::Lean => "lean",
      SourceCodeLanguage::Linkerscript => "linkerscript",
      SourceCodeLanguage::Liquid => "liquid",
      SourceCodeLanguage::Llvm => "llvm",
      SourceCodeLanguage::Lua => "lua",
      SourceCodeLanguage::Luau => "luau",
      SourceCodeLanguage::Magma => "magma",
      SourceCodeLanguage::Make => "make",
      SourceCodeLanguage::Markdown => "markdown",
      SourceCodeLanguage::Matlab => "matlab",
      SourceCodeLanguage::Mermaid => "mermaid",
      SourceCodeLanguage::Meson => "meson",
      SourceCodeLanguage::Mojo => "mojo",
      SourceCodeLanguage::Move => "move",
      SourceCodeLanguage::Nasm => "nasm",
      SourceCodeLanguage::Nickel => "nickel",
      SourceCodeLanguage::Nix => "nix",
      SourceCodeLanguage::Objc => "objc",
      SourceCodeLanguage::ObjectscriptRoutine => "objectscript_routine",
      SourceCodeLanguage::ObjectscriptUdl => "objectscript_udl",
      SourceCodeLanguage::Ocaml => "ocaml",
      SourceCodeLanguage::Odin => "odin",
      SourceCodeLanguage::Pascal => "pascal",
      SourceCodeLanguage::Perl => "perl",
      SourceCodeLanguage::Php => "php",
      SourceCodeLanguage::Pine => "pine",
      SourceCodeLanguage::Pkl => "pkl",
      SourceCodeLanguage::Po => "po",
      SourceCodeLanguage::Pony => "pony",
      SourceCodeLanguage::Powershell => "powershell",
      SourceCodeLanguage::Prisma => "prisma",
      SourceCodeLanguage::Properties => "properties",
      SourceCodeLanguage::Protobuf => "protobuf",
      SourceCodeLanguage::Puppet => "puppet",
      SourceCodeLanguage::Purescript => "purescript",
      SourceCodeLanguage::Qml => "qml",
      SourceCodeLanguage::R => "r",
      SourceCodeLanguage::Racket => "racket",
      SourceCodeLanguage::Regex => "regex",
      SourceCodeLanguage::Requirements => "requirements",
      SourceCodeLanguage::Rescript => "rescript",
      SourceCodeLanguage::Ron => "ron",
      SourceCodeLanguage::Rst => "rst",
      SourceCodeLanguage::Ruby => "ruby",
      SourceCodeLanguage::Scala => "scala",
      SourceCodeLanguage::Scheme => "scheme",
      SourceCodeLanguage::Scss => "scss",
      SourceCodeLanguage::Slang => "slang",
      SourceCodeLanguage::Smali => "smali",
      SourceCodeLanguage::Smithy => "smithy",
      SourceCodeLanguage::Solidity => "solidity",
      SourceCodeLanguage::Soql => "soql",
      SourceCodeLanguage::Sosl => "sosl",
      SourceCodeLanguage::Sql => "sql",
      SourceCodeLanguage::Squirrel => "squirrel",
      SourceCodeLanguage::Sshconfig => "sshconfig",
      SourceCodeLanguage::Starlark => "starlark",
      SourceCodeLanguage::Svelte => "svelte",
      SourceCodeLanguage::Sway => "sway",
      SourceCodeLanguage::Swift => "swift",
      SourceCodeLanguage::Systemverilog => "systemverilog",
      SourceCodeLanguage::Tablegen => "tablegen",
      SourceCodeLanguage::Tcl => "tcl",
      SourceCodeLanguage::Teal => "teal",
      SourceCodeLanguage::Templ => "templ",
      SourceCodeLanguage::Thrift => "thrift",
      SourceCodeLanguage::Tlaplus => "tlaplus",
      SourceCodeLanguage::Toml => "toml",
      SourceCodeLanguage::Tsx => "tsx",
      SourceCodeLanguage::TypeScript => "typescript",
      SourceCodeLanguage::Typst => "typst",
      SourceCodeLanguage::Verilog => "verilog",
      SourceCodeLanguage::Vhdl => "vhdl",
      SourceCodeLanguage::Vim => "vim",
      SourceCodeLanguage::Vue => "vue",
      SourceCodeLanguage::Wgsl => "wgsl",
      SourceCodeLanguage::Wit => "wit",
      SourceCodeLanguage::Wolfram => "wolfram",
      SourceCodeLanguage::Xml => "xml",
      SourceCodeLanguage::Yaml => "yaml",
      SourceCodeLanguage::Zig => "zig",
      SourceCodeLanguage::Zsh => "zsh",
    }
  }
}

impl From<&str> for SourceCodeLanguage {
  fn from(value: &str) -> Self {
    let filename = value.rsplit('/').next().unwrap_or(value).to_ascii_lowercase();

    if filename.ends_with(".d.ts") {
      return SourceCodeLanguage::TypeScript;
    }

    match filename.as_str() {
      "dockerfile" => return SourceCodeLanguage::Dockerfile,
      ".gitignore" => return SourceCodeLanguage::Gitignore,
      ".gitattributes" => return SourceCodeLanguage::Gitattributes,
      "blade.php" => return SourceCodeLanguage::Blade,
      "cls.xml" => return SourceCodeLanguage::ObjectscriptUdl,
      "makefile" | "gnumakefile" => return SourceCodeLanguage::Make,
      "cmakelists.txt" => return SourceCodeLanguage::Cmake,
      "justfile" => return SourceCodeLanguage::Just,
      "requirements.txt" => return SourceCodeLanguage::Requirements,
      "containerfile" => return SourceCodeLanguage::Dockerfile,
      "meson.build" | "meson_options.txt" => return SourceCodeLanguage::Meson,
      "go.mod" | "go.sum" => return SourceCodeLanguage::Gomod,
      _ => {}
    }

    match filename.rsplit('.').next() {
      Some("adb") | Some("ads") => SourceCodeLanguage::Ada,
      Some("agda") => SourceCodeLanguage::Agda,
      Some("cls") | Some("apex") => SourceCodeLanguage::Apex,
      Some("s") | Some("asm") => SourceCodeLanguage::Assembly,
      Some("astro") => SourceCodeLanguage::Astro,
      Some("awk") => SourceCodeLanguage::Awk,
      Some("sh") | Some("bash") => SourceCodeLanguage::Bash,
      Some("beancount") => SourceCodeLanguage::Beancount,
      Some("bib") => SourceCodeLanguage::Bibtex,
      Some("bicep") => SourceCodeLanguage::Bicep,
      Some("bb") | Some("bbappend") => SourceCodeLanguage::Bitbake,
      Some("c") | Some("h") => SourceCodeLanguage::C,
      Some("cs") => SourceCodeLanguage::CSharp,
      Some("cairo") => SourceCodeLanguage::Cairo,
      Some("capnp") => SourceCodeLanguage::Capnp,
      Some("cfm") => SourceCodeLanguage::Cfml,
      Some("cfc") => SourceCodeLanguage::Cfscript,
      Some("clj") | Some("cljc") | Some("cljs") => SourceCodeLanguage::Clojure,
      Some("cmake") => SourceCodeLanguage::Cmake,
      Some("cob") | Some("cbl") => SourceCodeLanguage::Cobol,
      Some("lisp") | Some("lsp") => SourceCodeLanguage::Commonlisp,
      Some("cc") | Some("cp") | Some("cxx") | Some("cpp") | Some("hpp") | Some("hxx") => {
        SourceCodeLanguage::Cpp
      }
      Some("cr") => SourceCodeLanguage::Crystal,
      Some("css") => SourceCodeLanguage::Css,
      Some("csv") => SourceCodeLanguage::Csv,
      Some("cu") | Some("cuh") => SourceCodeLanguage::Cuda,
      Some("d") => SourceCodeLanguage::D,
      Some("dart") => SourceCodeLanguage::Dart,
      Some("dts") | Some("dtsi") => SourceCodeLanguage::Devicetree,
      Some("diff") | Some("patch") => SourceCodeLanguage::Diff,
      Some("env") => SourceCodeLanguage::Dotenv,
      Some("el") => SourceCodeLanguage::Elisp,
      Some("ex") | Some("exs") => SourceCodeLanguage::Elixir,
      Some("elm") => SourceCodeLanguage::Elm,
      Some("erl") | Some("hrl") => SourceCodeLanguage::Erlang,
      Some("fnl") => SourceCodeLanguage::Fennel,
      Some("fish") => SourceCodeLanguage::Fish,
      Some("form") => SourceCodeLanguage::Form,
      Some("f") | Some("f90") | Some("f95") => SourceCodeLanguage::Fortran,
      Some("fs") | Some("fsi") | Some("fsx") => SourceCodeLanguage::FSharp,
      Some("gd") => SourceCodeLanguage::Gdscript,
      Some("gleam") => SourceCodeLanguage::Gleam,
      Some("glsl") | Some("frag") | Some("vert") => SourceCodeLanguage::Glsl,
      Some("gn") | Some("gni") => SourceCodeLanguage::Gn,
      Some("go") => SourceCodeLanguage::Go,
      Some("gotmpl") => SourceCodeLanguage::Gotemplate,
      Some("graphql") | Some("gql") => SourceCodeLanguage::Graphql,
      Some("groovy") | Some("gradle") => SourceCodeLanguage::Groovy,
      Some("ha") | Some("hs") => SourceCodeLanguage::Haskell,
      Some("hcl") | Some("tf") | Some("tfvars") => SourceCodeLanguage::Hcl,
      Some("hlsl") => SourceCodeLanguage::Hlsl,
      Some("html") | Some("htm") => SourceCodeLanguage::Html,
      Some("hypr") => SourceCodeLanguage::Hyprlang,
      Some("ini") => SourceCodeLanguage::Ini,
      Some("ispc") => SourceCodeLanguage::Ispc,
      Some("janet") => SourceCodeLanguage::Janet,
      Some("java") => SourceCodeLanguage::Java,
      Some("js") | Some("mjs") | Some("cjs") => SourceCodeLanguage::JavaScript,
      Some("jinja") | Some("jinja2") | Some("j2") => SourceCodeLanguage::Jinja2,
      Some("json") => SourceCodeLanguage::Json,
      Some("json5") => SourceCodeLanguage::Json5,
      Some("jsonnet") | Some("libsonnet") => SourceCodeLanguage::Jsonnet,
      Some("jl") => SourceCodeLanguage::Julia,
      Some("kconfig") => SourceCodeLanguage::Kconfig,
      Some("kdl") => SourceCodeLanguage::Kdl,
      Some("kt") | Some("kts") => SourceCodeLanguage::Kotlin,
      Some("lean") => SourceCodeLanguage::Lean,
      Some("ld") | Some("lds") => SourceCodeLanguage::Linkerscript,
      Some("liquid") => SourceCodeLanguage::Liquid,
      Some("ll") => SourceCodeLanguage::Llvm,
      Some("lua") => SourceCodeLanguage::Lua,
      Some("luau") => SourceCodeLanguage::Luau,
      Some("m") => SourceCodeLanguage::Objc,
      Some("md") | Some("mdx") => SourceCodeLanguage::Markdown,
      Some("mat") => SourceCodeLanguage::Matlab,
      Some("mmd") => SourceCodeLanguage::Mermaid,
      Some("meson") => SourceCodeLanguage::Meson,
      Some("mojo") => SourceCodeLanguage::Mojo,
      Some("move") => SourceCodeLanguage::Move,
      Some("nasm") => SourceCodeLanguage::Nasm,
      Some("ncl") => SourceCodeLanguage::Nickel,
      Some("nix") => SourceCodeLanguage::Nix,
      Some("mac") => SourceCodeLanguage::ObjectscriptRoutine,
      Some("ml") | Some("mli") => SourceCodeLanguage::Ocaml,
      Some("odin") => SourceCodeLanguage::Odin,
      Some("pas") => SourceCodeLanguage::Pascal,
      Some("pl") | Some("pm") => SourceCodeLanguage::Perl,
      Some("php") => SourceCodeLanguage::Php,
      Some("pine") => SourceCodeLanguage::Pine,
      Some("pkl") => SourceCodeLanguage::Pkl,
      Some("po") => SourceCodeLanguage::Po,
      Some("pony") => SourceCodeLanguage::Pony,
      Some("ps1") | Some("psm1") => SourceCodeLanguage::Powershell,
      Some("prisma") => SourceCodeLanguage::Prisma,
      Some("properties") => SourceCodeLanguage::Properties,
      Some("proto") => SourceCodeLanguage::Protobuf,
      Some("pp") => SourceCodeLanguage::Puppet,
      Some("purs") => SourceCodeLanguage::Purescript,
      Some("py") => SourceCodeLanguage::Python,
      Some("qml") => SourceCodeLanguage::Qml,
      Some("r") => SourceCodeLanguage::R,
      Some("rkt") => SourceCodeLanguage::Racket,
      Some("regex") => SourceCodeLanguage::Regex,
      Some("res") | Some("resi") => SourceCodeLanguage::Rescript,
      Some("ron") => SourceCodeLanguage::Ron,
      Some("rst") => SourceCodeLanguage::Rst,
      Some("rb") => SourceCodeLanguage::Ruby,
      Some("rs") => SourceCodeLanguage::Rust,
      Some("scala") => SourceCodeLanguage::Scala,
      Some("scm") | Some("ss") => SourceCodeLanguage::Scheme,
      Some("scss") => SourceCodeLanguage::Scss,
      Some("slang") => SourceCodeLanguage::Slang,
      Some("smali") => SourceCodeLanguage::Smali,
      Some("smithy") => SourceCodeLanguage::Smithy,
      Some("sol") => SourceCodeLanguage::Solidity,
      Some("soql") => SourceCodeLanguage::Soql,
      Some("sosl") => SourceCodeLanguage::Sosl,
      Some("sql") => SourceCodeLanguage::Sql,
      Some("nut") => SourceCodeLanguage::Squirrel,
      Some("sshconfig") => SourceCodeLanguage::Sshconfig,
      Some("star") => SourceCodeLanguage::Starlark,
      Some("svelte") => SourceCodeLanguage::Svelte,
      Some("sway") => SourceCodeLanguage::Sway,
      Some("swift") => SourceCodeLanguage::Swift,
      Some("sv") | Some("svh") => SourceCodeLanguage::Systemverilog,
      Some("td") => SourceCodeLanguage::Tablegen,
      Some("tcl") => SourceCodeLanguage::Tcl,
      Some("tl") => SourceCodeLanguage::Teal,
      Some("templ") => SourceCodeLanguage::Templ,
      Some("thrift") => SourceCodeLanguage::Thrift,
      Some("tla") => SourceCodeLanguage::Tlaplus,
      Some("toml") => SourceCodeLanguage::Toml,
      Some("tsx") => SourceCodeLanguage::Tsx,
      Some("ts") => SourceCodeLanguage::TypeScript,
      Some("typ") => SourceCodeLanguage::Typst,
      Some("v") => SourceCodeLanguage::Verilog,
      Some("vhd") | Some("vhdl") => SourceCodeLanguage::Vhdl,
      Some("vim") => SourceCodeLanguage::Vim,
      Some("vue") => SourceCodeLanguage::Vue,
      Some("wgsl") => SourceCodeLanguage::Wgsl,
      Some("wit") => SourceCodeLanguage::Wit,
      Some("wl") | Some("wls") => SourceCodeLanguage::Wolfram,
      Some("xml") => SourceCodeLanguage::Xml,
      Some("yml") | Some("yaml") => SourceCodeLanguage::Yaml,
      Some("zig") => SourceCodeLanguage::Zig,
      Some("zsh") => SourceCodeLanguage::Zsh,
      _ => SourceCodeLanguage::TypeScript,
    }
  }
}

impl From<String> for SourceCodeLanguage {
  fn from(value: String) -> Self {
    Self::from(value.as_str())
  }
}

impl From<&Path> for SourceCodeLanguage {
  fn from(value: &Path) -> Self {
    Self::from(value.to_str().unwrap_or_default())
  }
}

impl From<&PathBuf> for SourceCodeLanguage {
  fn from(value: &PathBuf) -> Self {
    Self::from(value.as_path())
  }
}

/// A source code item.
#[derive(Debug, Clone, Default, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct SourceCode {
  /// The language of the source code.
  pub language: SourceCodeLanguage,
  /// The content of the source code.
  pub content: String,
}

impl SourceCode {
  /// Create a new source code.
  pub fn new(language: SourceCodeLanguage, content: String) -> Self {
    Self { language, content }
  }
}
