/* -------------------------------------------------------------------

                  🗲 Storm Software - Power Plant

 This code was released as part of the Power Plant project. Power Plant
 is maintained by Storm Software under the Apache-2.0 license, and is
 free for commercial and private use. For more information, please visit
 our licensing page at https://stormsoftware.com/licenses/projects/power-plant.

 Website:                  https://stormsoftware.com
 Repository:               https://github.com/storm-software/power-plant
 Documentation:            https://docs.stormsoftware.com/projects/power-plant
 Contact:                  https://stormsoftware.com/contact

 SPDX-License-Identifier:  Apache-2.0

 ------------------------------------------------------------------- */

import type { SchemaConfig } from "@power-plant/schema";
import type { InferLoadOptions, LoadReference } from "@stryke/resolve/types";
import type { DeepPartial, MaybePromise } from "@stryke/types/base";
import type { UserConfig } from "./config";
import type { Input, InputConfig } from "./input";
import type { MetaConfig } from "./meta";
import type { Output, OutputConfig } from "./output";
import type { SchemaConfigObject, SchemaOf } from "./schema";

export interface GeneratedDocumentChunk {
  content?: string;
  meta?: MetaConfig;
}

export interface GeneratedDocument {
  path: string;
  language?: string;
  chunks?: DeepPartial<GeneratedDocumentChunk>[];
  meta?: MetaConfig;
}

export type GeneratorFunction<TSpec, TOptions extends object> = (
  spec: TSpec,
  options: TOptions
) => MaybePromise<Record<string, GeneratedDocument>>;

export type GeneratorFunctionResult<TSpec, TOptions extends object> = Awaited<
  ReturnType<GeneratorFunction<TSpec, TOptions>>
>;

export interface GeneratorResult<
  TSpec,
  TOptions extends object,
  TReturns = void
> {
  /**
   * The specification used to generate the documents.
   */
  spec: TSpec;

  /**
   * The options used to generate the documents.
   */
  options: TOptions;

  /**
   * The documents generated by the generator.
   */
  documents: GeneratorFunctionResult<TSpec, TOptions>;

  /**
   * The return value from the output function.
   */
  returns: TReturns;
}

export interface GeneratorConfigObject<
  TSpec,
  TOptions extends object,
  TReturns = void
> {
  /**
   * Optional metadata about the generator, such as a description of the output it produces.
   */
  meta?: MetaConfig;

  /**
   * The schema config that defines the structure of the specification object for this generator.
   */
  schema?: SchemaConfig<TSpec> | SchemaConfigObject<TSpec>;

  /**
   * The input config for the generator specification.
   */
  input?: InputConfig<TSpec, TOptions>;

  /**
   * The output config that consumes generated output.
   */
  output?: OutputConfig<TSpec, TOptions, TReturns>;

  /**
   * The generate implementation, either as a callable function or a file reference.
   */
  generator: GeneratorFunction<TSpec, TOptions> | LoadReference;
}

export type GeneratorConfig<TSpec, TOptions extends object, TReturns = void> =
  LoadReference | GeneratorConfigObject<TSpec, TOptions, TReturns>;

export type InferCreateGeneratorOptions<
  T extends GeneratorConfig<any, any, any>
> = (T extends LoadReference
  ? InferLoadOptions<T>
  : // eslint-disable-next-line ts/no-empty-object-type
    {}) & { tsconfig?: string };

export interface Generator<TSpec, TOptions extends object, TReturns = void> {
  /**
   * Optional metadata about the generator, such as a description of the output it produces.
   */
  meta?: MetaConfig;

  /**
   * The schema config that defines the structure of the specification object for this generator.
   */
  schema: SchemaOf<TSpec>;

  /**
   * The input of the generator, which can be used to specify where the generator retrieves its input data from. This can be defined as a function that takes the specification and returns a value, or it can be a static value.
   */
  input: Input<TSpec, TOptions>;

  /**
   * The output of the generator, which can be used to specify where the generator sends its output data. This can be defined as a function that takes the specification and returns a value, or it can be a static value.
   */
  output: Output<TSpec, TOptions, TReturns>;

  /**
   * The generator function that executes the generator logic, taking in options and producing output based on the input and output definitions.
   *
   * @remarks
   * The generator function is responsible for orchestrating the generation process. It takes in options that can influence the generation behavior and returns a promise that resolves to the result of the generator execution, which includes the generated output and any additional metadata.
   *
   * @param options - The options to be passed to the generator, which can be used to influence the generation process.
   * @returns A promise that resolves to the result of the generator execution, which includes the generated output and any additional metadata.
   */
  generator: (
    options: TOptions & UserConfig
  ) => Promise<GeneratorResult<TSpec, TOptions, TReturns>>;
}

export type InferSchemaConfig<T extends GeneratorConfig<any, any, any>> =
  T extends LoadReference
    ? InferLoadOptions<T>
    : T extends GeneratorConfigObject<any, any, any>
      ? T["schema"]
      : never;

export type InferMeta<T extends GeneratorConfig<any, any, any>> =
  T extends LoadReference
    ? InferLoadOptions<T>
    : T extends GeneratorConfigObject<any, any, any>
      ? T["meta"]
      : never;

export type InferInputConfig<T extends GeneratorConfig<any, any, any>> =
  T extends LoadReference
    ? InferLoadOptions<T>
    : T extends GeneratorConfigObject<any, any, any>
      ? T["input"]
      : never;

export type InferOutputConfig<T extends GeneratorConfig<any, any, any>> =
  T extends LoadReference
    ? InferLoadOptions<T>
    : T extends GeneratorConfigObject<any, any, any>
      ? T["output"]
      : never;

export type InferGeneratorFunction<T extends GeneratorConfig<any, any, any>> =
  T extends LoadReference
    ? InferLoadOptions<T>
    : T extends GeneratorConfigObject<any, any, any>
      ? T["generator"]
      : never;

export type InferGeneratorResult<T extends GeneratorConfig<any, any, any>> =
  InferGeneratorFunction<T> extends GeneratorFunction<any, any>
    ? Awaited<ReturnType<InferGeneratorFunction<T>>>
    : never;

export interface InferGenerator<T extends GeneratorConfig<any, any, any>> {
  meta?: InferMeta<T>;
  schema: InferSchemaConfig<T>;
  input: InferInputConfig<T>;
  output: InferOutputConfig<T>;
  generator: InferGeneratorFunction<T>;
}
