[package]
authors       = { workspace = true }
build         = 'build.rs'
categories    = { workspace = true }
description   = '☢️ Utility types and functions used across the Power Plant runtime.'
documentation = 'https://docs.rs/power-plant'
edition       = { workspace = true }
homepage      = { workspace = true }
keywords      = { workspace = true }
license       = { workspace = true }
name          = 'power-plant-tree-sitter'
publish       = true
readme        = './README.md'
repository    = { workspace = true }
version       = '0.1.7'

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
glob        = { workspace = true }
serde_json  = { workspace = true }
tree-sitter = { workspace = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
rayon = { workspace = true }

[build-dependencies]
cc         = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
