[package]
authors       = { workspace = true }
build         = 'build.rs'
categories    = { workspace = true }
description   = '☢️ Utility types and functions used across the Power Plant runtime.'
documentation = 'https://docs.rs/power-plant'
edition       = { workspace = true }
homepage      = { workspace = true }
keywords      = { workspace = true }
license       = { workspace = true }
name          = 'power-plant-tree-sitter'
private       = false
publish       = true
readme        = './README.md'
repository    = { workspace = true }
version       = '0.1.4'

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
base-encode = { workspace = true }
base64-simd = { workspace = true }
cow-utils   = { workspace = true }
dashmap     = { workspace = true }
futures     = { workspace = true }
glob        = { workspace = true }
infer       = { workspace = true }
memchr      = { workspace = true }
nom         = { workspace = true }
regex       = { workspace = true }
regress     = { workspace = true }
serde       = { workspace = true }
serde_json  = { workspace = true }
tokio       = { workspace = true, features = ['sync'] }
tree-sitter = { workspace = true }
uuid        = { workspace = true, features = ['v4'] }
xxhash-rust = { workspace = true, features = ['xxh3'] }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
async-scoped = { workspace = true, features = ['use-tokio'] }
rayon        = { workspace = true }

[build-dependencies]
bindgen    = { workspace = true }
cc         = { workspace = true }
glob       = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
