[package]
authors       = { workspace = true }
categories    = { workspace = true }
description   = '☢️ Text generation that gives your AI superpowers.'
documentation = 'https://docs.rs/power-plant'
edition       = { workspace = true }
homepage      = { workspace = true }
keywords      = { workspace = true }
license       = { workspace = true }
name          = 'power-plant-engine'
publish       = true
readme        = './README.md'
repository    = { workspace = true }
version       = '0.1.6'

[package.metadata.cargo-shear]
ignored = ['serde', 'serde_json']

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
camino              = { workspace = true }
derive_more         = { workspace = true }
power-plant-core    = { workspace = true }
power-plant-models  = { workspace = true }
power-plant-storage = { workspace = true }
serde               = { workspace = true, features = ['derive'], optional = true }
serde_json          = { workspace = true }
thiserror           = { workspace = true }
tracing             = { workspace = true }

[features]
default      = ['serde']
experimental = []
ladybug      = ['power-plant-storage/ladybug']
serde        = ['dep:serde']
testing      = []

[dev-dependencies]
chrono              = { workspace = true, features = ['serde'] }
power-plant-models  = { workspace = true }
power-plant-storage = { workspace = true, features = ['testing'] }
serde_json          = { workspace = true }
