name: "Release"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: override release tag
        required: false
  push:
    branches:
      - main
      - next
      - experimental

env:
  CI: true
  DEBUG: napi:*
  MACOSX_DEPLOYMENT_TARGET: "10.13"
  CARGO_INCREMENTAL: "1"
  STORM_REPOSITORY: ${{ github.repositoryUrl }}
  STORM_WORKSPACE_ROOT: ${{ github.workspace }}
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_REPOSITORY: ${{ github.repository }}
  GITHUB_TOKEN: ${{ github.token }}
  NPM_TOKEN: ${{ secrets.STORM_BOT_NPM_TOKEN }}

jobs:
  start:
    name: "Send in progress notification"
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
      id-token: write
    if: github.repository == 'storm-software/power-plant' && (github.ref ==
      'refs/heads/main' || github.ref == 'refs/heads/next' || github.ref ==
      'refs/heads/experimental')
    steps:
      - name: Send notification - Deployment started
        uses: storm-software/action-notify@main
        with:
          title: "Deployment for ${{ github.repository }} has started (In Progress)"
          subtitle: "Deployment for ${{ github.repository }} has started - #${{
            github.run_number }}"
          description:
            "Deployment for ${{ github.repository }} is currently in progress -
            #${{ github.run_number }}. Click here to view the changes associated
            with this deployment: ${{ github.event.pull_request.html_url ||
            github.event.head_commit.url }} "
          color: 2077350
          status: "In Progress"
          slack-token: ${{ secrets.STORM_BOT_SLACK_TOKEN }}
          telegram-token: ${{ secrets.STORM_BOT_TELEGRAM_TOKEN }}
          telegram-chat: ${{ secrets.STORM_BOT_TELEGRAM_NOTIFICATION_CHAT }}
          discord-webhook: ${{ secrets.STORM_BOT_DISCORD_WEBHOOK}}

  build-bindings-unix:
    name: Build bindings - ${{ matrix.target }}
    if: always() && !cancelled() && !contains(needs.*.result, 'failure') &&
      github.event.pull_request.draft == false
    runs-on: ${{ matrix.host }}
    environment: production
    permissions:
      contents: write
      id-token: write
    needs:
      - start
    strategy:
      fail-fast: false
      matrix:
        include:
          - host: macos-latest
            target: x86_64-apple-darwin
            build-flags: ""
            profile: native-darwin
          - host: macos-latest
            target: aarch64-apple-darwin
            build-flags: ""
            profile: native-darwin
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            build-flags: --use-napi-cross
            profile: native-linux
          - host: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            build-flags: --use-napi-cross
            profile: native-linux
          - host: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            build-flags: --use-napi-cross
            profile: native-linux
          - host: ubuntu-latest
            target: x86_64-unknown-linux-musl
            build-flags: -x
            profile: native-linux-musl
          - host: ubuntu-latest
            target: aarch64-unknown-linux-musl
            build-flags: -x
            profile: native-linux-musl
          - host: ubuntu-latest
            target: aarch64-linux-android
            build-flags: ""
            profile: native-linux
          - host: ubuntu-latest
            target: aarch64-unknown-linux-ohos
            build-flags: --use-napi-cross
            profile: native-linux
          - host: ubuntu-latest
            target: wasm32-wasip1-threads
            build-flags: ""
            profile: native-linux
          - host: ubuntu-latest
            target: s390x-unknown-linux-gnu
            build-flags: --use-napi-cross
            profile: native-linux
          - host: ubuntu-latest
            target: powerpc64le-unknown-linux-gnu
            build-flags: --use-napi-cross
            profile: native-linux
    steps:
      - name: Setup workspace
        uses: storm-software/action-devenv-setup@main
        with:
          gpg-sign-key: ${{ secrets.STORM_BOT_GPG_SIGN_KEY }}
          gpg-private-key: ${{ secrets.STORM_BOT_GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.STORM_BOT_GPG_PASSPHRASE }}
          storm-bot-github-token: ${{ secrets.STORM_BOT_GITHUB_TOKEN }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build native binding
        run: devenv --profile production --profile ${{ matrix.profile }} --no-tui shell build-native ${{ matrix.target }} ${{ matrix.build-flags }}
        env:
          NATIVE_TARGET: ${{ matrix.target }}
          NATIVE_BUILD_FLAGS: ${{ matrix.build-flags }}
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v4.6.2
        with:
          name: bindings-${{ matrix.target }}
          path: packages/base/bindings/src/power-plant-bindings.*
          if-no-files-found: error

      - name: Upload artifact - Unix
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v4.6.2
        if: matrix.target != 'wasm32-wasip1-threads'
        with:
          name: bindings-${{ matrix.target }}
          path: packages/base/bindings/src/*.node
          if-no-files-found: error

      - name: Upload artifact - WASM
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v4.6.2
        if: matrix.target == 'wasm32-wasip1-threads'
        with:
          name: bindings-${{ matrix.target }}
          path: packages/base/bindings/src/*.wasm
          if-no-files-found: error

  build-bindings-windows:
    name: Build bindings - ${{ matrix.target }}
    if: always() && !cancelled() && !contains(needs.*.result, 'failure') &&
      github.event.pull_request.draft == false
    runs-on: ${{ matrix.host }}
    environment: production
    permissions:
      contents: write
      id-token: write
    needs:
      - start
    strategy:
      fail-fast: false
      matrix:
        include:
          - host: windows-latest
            target: x86_64-pc-windows-msvc
          - host: windows-latest
            target: aarch64-pc-windows-msvc
          - host: windows-latest
            target: i686-pc-windows-msvc
    steps:
      - name: Setup workspace
        uses: storm-software/action-setup@main
        with:
          gpg-sign-key: ${{ secrets.STORM_BOT_GPG_SIGN_KEY }}
          gpg-private-key: ${{ secrets.STORM_BOT_GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.STORM_BOT_GPG_PASSPHRASE }}
          storm-bot-github-token: ${{ secrets.STORM_BOT_GITHUB_TOKEN }}

      - name: Install
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Cache cargo
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.napi-rs
            .cargo-cache
            target/
          key: ${{ matrix.target }}-cargo-${{ matrix.host }}

      - name: Setup toolchain
        run: ${{ matrix.setup }}
        if: ${{ matrix.setup }}
        shell: bash

      - name: Setup node x86
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        if: matrix.target == 'i686-pc-windows-msvc'
        with:
          cache: pnpm
          architecture: x86

      - name: Build
        run: pnpm build-native --target ${{ matrix.target }}
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v4.6.2
        with:
          name: bindings-${{ matrix.target }}
          path: packages/base/bindings/src/*.node
          if-no-files-found: error

  build-bindings-freebsd:
    name: Build bindings - x86_64-unknown-freebsd
    if: always() && !cancelled() && !contains(needs.*.result, 'failure') &&
      github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
      id-token: write
    needs:
      - start
    steps:
      - name: Setup workspace
        uses: storm-software/action-setup@main
        with:
          gpg-sign-key: ${{ secrets.STORM_BOT_GPG_SIGN_KEY }}
          gpg-private-key: ${{ secrets.STORM_BOT_GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.STORM_BOT_GPG_PASSPHRASE }}
          storm-bot-github-token: ${{ secrets.STORM_BOT_GITHUB_TOKEN }}

      - name: Build on FreeBSD
        uses: cross-platform-actions/action@5ea7e8e4677bd726033a10b094ba1c5762b15dee # v1.3.0
        env:
          DEBUG: napi:*
          RUSTUP_IO_THREADS: 1
        with:
          operating_system: freebsd
          version: "15.0"
          memory: 8G
          cpu_count: 3
          environment_variables: DEBUG RUSTUP_IO_THREADS
          shell: bash
          run: |
            sudo pkg install -y -f curl node libnghttp2 npm
            sudo npm install -g corepack
            curl https://sh.rustup.rs -sSf --output rustup.sh
            sh rustup.sh -y --profile minimal --default-toolchain stable
            sudo corepack enable
            source "$HOME/.cargo/env"
            pnpm install --frozen-lockfile
            cd packages/base/bindings
            pnpm exec napi build --release \
              --cwd ./src \
              --manifest-path ../../../../crates/bindings/Cargo.toml \
              --package-json-path ../package.json \
              --target x86_64-unknown-freebsd

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v4.6.2
        with:
          name: bindings-x86_64-unknown-freebsd
          path: packages/base/bindings/src/*.node
          if-no-files-found: error

  release:
    name: "Release"
    if: always() && !cancelled() && !contains(needs.*.result, 'failure') &&
      github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
      id-token: write
    needs:
      - start
      - build-bindings-unix
      - build-bindings-windows
      - build-bindings-freebsd
    steps:
      - name: Setup workspace
        uses: storm-software/action-devenv-setup@main
        with:
          gpg-sign-key: ${{ secrets.STORM_BOT_GPG_SIGN_KEY }}
          gpg-private-key: ${{ secrets.STORM_BOT_GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.STORM_BOT_GPG_PASSPHRASE }}
          storm-bot-github-token: ${{ secrets.STORM_BOT_GITHUB_TOKEN }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        id: setSHAs
        uses: nrwl/nx-set-shas@3e9ad7370203c1e93d109be57f3b72eb0eb511b1 # v4.4.0
        with:
          main-branch-name: main
          workflow-id: release.yml
          set-environment-variables-for-job: true
          error-on-no-successful-workflow: false

      - name: Download binding artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b4d8f34e9478ee7ad3464f1c # v4.3.0
        with:
          path: packages/base/bindings/artifacts
          pattern: bindings-*
          merge-multiple: true

      - name: Deploy binding artifacts to npm dirs
        run: pnpm nx run bindings:deploy-artifacts

      - name: Release repository updates
        run: devenv --profile production --no-tui shell release ${{
          steps.setSHAs.outputs.base }} ${{ steps.setSHAs.outputs.head }}
        env:
          NX_BASE: ${{ steps.setSHAs.outputs.base }}
          NX_HEAD: ${{ steps.setSHAs.outputs.head }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ github.token }}
          STORM_BOT_GITHUB_TOKEN: ${{ secrets.STORM_BOT_GITHUB_TOKEN }}
          STORM_WORKSPACE_ROOT: ${{ github.workspace }}
          STORM_REPOSITORY: ${{ github.repositoryUrl }}
          NPM_TOKEN: ${{ secrets.STORM_BOT_NPM_TOKEN }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.STORM_BOT_CLOUDFLARE_TOKEN }}
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
          TAG: ${{ inputs.tag }}

  success:
    needs:
      - release
    if: ${{ success() }}
    name: Send success notification
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Send notification - Deployment successful
        uses: storm-software/action-notify@main
        with:
          title: "Deployment for ${{ github.repository }} has finished (Success)"
          subtitle:
            "Deployment for ${{ github.repository }} has finished successfully -
            #${{ github.run_number }}"
          description:
            "Deployment for ${{ github.repository }} has finished successfully
            - #${{ github.run_number }}. Click here to view the changes
            associated with this deployment: ${{
            github.event.pull_request.html_url || github.event.head_commit.url
            }} "
          color: 556891
          status: "Success"
          slack-token: ${{ secrets.STORM_BOT_SLACK_TOKEN }}
          telegram-token: ${{ secrets.STORM_BOT_TELEGRAM_TOKEN }}
          telegram-chat: ${{ secrets.STORM_BOT_TELEGRAM_NOTIFICATION_CHAT }}
          discord-webhook: ${{ secrets.STORM_BOT_DISCORD_WEBHOOK}}

  failure:
    needs:
      - release
    if: ${{ failure() }}
    name: Send failure notification
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Send notification - Deployment failed
        uses: storm-software/action-notify@main
        with:
          title: "Deployment for ${{ github.repository }} has finished (Failure)"
          subtitle:
            "Deployment for ${{ github.repository }} finished with failures - #${{
            github.run_number }}"
          description:
            "Deployment for ${{ github.repository }} finished with failures -
            #${{ github.run_number }}. Click here to view the changes associated
            with this deployment: ${{ github.event.pull_request.html_url ||
            github.event.head_commit.url }} "
          color: 10027008
          status: "Failure"
          slack-token: ${{ secrets.STORM_BOT_SLACK_TOKEN }}
          telegram-token: ${{ secrets.STORM_BOT_TELEGRAM_TOKEN }}
          telegram-chat: ${{ secrets.STORM_BOT_TELEGRAM_NOTIFICATION_CHAT }}
          discord-webhook: ${{ secrets.STORM_BOT_DISCORD_WEBHOOK}}

  cancelled:
    needs:
      - release
    if: ${{ cancelled() }}
    name: Send cancelled notification
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Send notification - Deployment cancelled
        uses: storm-software/action-notify@main
        with:
          title: "Deployment for ${{ github.repository }} has finished (Cancelled)"
          subtitle:
            "Deployment for ${{ github.repository }} has been cancelled - #${{
            github.run_number }}"
          description:
            "Deployment for ${{ github.repository }} was stopped before it
            could complete - #${{ github.run_number }}. Click here to view the
            changes associated with this deployment: ${{
            github.event.pull_request.html_url || github.event.head_commit.url
            }}."
          color: 16565273
          status: "Cancelled"
          slack-token: ${{ secrets.STORM_BOT_SLACK_TOKEN }}
          telegram-token: ${{ secrets.STORM_BOT_TELEGRAM_TOKEN }}
          telegram-chat: ${{ secrets.STORM_BOT_TELEGRAM_NOTIFICATION_CHAT }}
          discord-webhook: ${{ secrets.STORM_BOT_DISCORD_WEBHOOK}}
